Add test-packages/example.different with module example.somethingelse.
This leads to errors, which is exactly what I expect.  For example:

```
Error in test test_get_zcml_file_default (example.somethingelse.tests.TestPackage)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.8.5/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.8.5/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.8.5/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/src/plone/autoinclude/tests/package_base.py", line 46, in test_get_zcml_file_default
    filename = get_zcml_file(self.project_name)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/src/plone/autoinclude/loader.py", line 57, in get_zcml_file
    filename = resource_filename(project_name, zcml)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1128, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/py38/lib/python3.8/site-packages/pkg_resources/__init__.py", line 345, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'example.different'
```

`z3c.autoinclude` supports this by doing all kinds of tricks for finding the actual module.
We do not want this in `plone.autoinclude`.

My take on this:

1. This should not cause breakage.
   At most, the user should see a warning when we cannot find a module.

2. We want to add our own entry point where packages can explicitly arrange this.