Tox: do not set SETUPTOOLS_USE_DISTUTILS=stdlib in Buildout test env.
This was an old workaround for 'TypeError: dist must be a Distribution instance' on GHA.

Now suddenly this old workaround causes an error, on Python 3.12+:

```
$ tox -e buildout
buildout: commands_pre[0]> python -m pip list
Package     Version
----------- -------
packaging   24.2
pip         25.0.1
setuptools  75.8.0
wheel       0.45.1
zc.buildout 4.0
buildout: commands_pre[1]> .tox/buildout/bin/buildout -nc /Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/buildout.cfg buildout:directory=/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout
/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/_distutils_hack/__init__.py:53: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/bin/buildout", line 5, in <module>
    from zc.buildout.buildout import main
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/zc/buildout/__init__.py", line 21, in <module>
    import setuptools
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/__init__.py", line 24, in <module>
    from . import logging, monkey
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/logging.py", line 5, in <module>
    from . import monkey
  File "/Users/maurits/community/plone-coredev/6.2/src/plone.autoinclude/.tox/buildout/lib/python3.12/site-packages/setuptools/monkey.py", line 13, in <module>
    import distutils.filelist
ModuleNotFoundError: No module named 'distutils'
```