Test native and pkgutil namespaces.
Fixes https://github.com/plone/plone.autoinclude/issues/4
For background on the three different styles of namespace packages, see
https://packaging.python.org/guides/packaging-namespace-packages
In Plone land we are used to pkg_resources-style namespace packages.
These are not compatible with the other two methods.
So our example.* packages will only use pkg_resources-style namespace packages.
The other two styles are largely compatible, so we test them both in two namespaceexample.* packages.

Added python 3.10 to tox/actions.

For completeness, let me note a problem on my Mac, including a solution.
Strangely, `tox -e pypy3-integration` takes one and a half minute now on my Mac and fails due to too many open files.
This might fail only now because two new test packages are there.
Let me print the full run:

```
$ time tox -e pypy3-integration
pypy3-integration create: /Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration
pypy3-integration installdeps: zope.testrunner, -e., -etest-packages/example.basetestpackage, -etest-packages/example.addon, -etest-packages/example.different, -etest-packages/example.different2, -etest-packages/example.metaoverrides, -etest-packages/example.ploneaddon, -etest-packages/example.ploneintegration, -etest-packages/example.zopeaddon, -etest-packages/example.zopeintegration, -etest-packages/example.multipleeps, -etest-packages/namespaceexample.native, -etest-packages/namespaceexample.pkgutilns
ERROR: invocation failed (exit code 1), logfile: /Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/log/pypy3-integration-1.log
================================================================================================================ log start =================================================================================================================
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.basetestpackage
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.addon
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.different
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.different2
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.metaoverrides
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.ploneaddon
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.ploneintegration
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.zopeaddon
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.zopeintegration
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/example.multipleeps
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/namespaceexample.native
Obtaining file:///Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/test-packages/namespaceexample.pkgutilns
Collecting zope.testrunner
  Using cached zope.testrunner-5.3.0-py2.py3-none-any.whl (215 kB)
Requirement already satisfied: setuptools in ./.tox/pypy3-integration/site-packages (from zope.testrunner) (58.0.4)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting zope.exceptions
  Using cached zope.exceptions-4.4-py2.py3-none-any.whl (18 kB)
Collecting zope.interface
  Using cached zope.interface-5.4.0-py3-none-any.whl
Collecting zope.configuration
  Using cached zope.configuration-4.4.0-py2.py3-none-any.whl (79 kB)
Collecting zope.i18nmessageid
  Using cached zope.i18nmessageid-5.0.1-py3-none-any.whl
Collecting zope.schema>=4.9
  Using cached zope.schema-6.1.0-py2.py3-none-any.whl (85 kB)
Collecting zope.event
  Using cached zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: zope.interface, zope.event, six, zope.schema, zope.i18nmessageid, zope.configuration, zope.exceptions, plone.autoinclude, zope.testrunner, namespaceexample.pkgutilns, namespaceexample.native, example.zopeintegration, example.zopeaddon, example.ploneintegration, example.ploneaddon, example.multipleeps, example.metaoverrides, example.different2, example.different, example.basetestpackage, example.addon
  Running setup.py develop for plone.autoinclude
  Running setup.py develop for namespaceexample.pkgutilns
  Running setup.py develop for namespaceexample.native
  Running setup.py develop for example.zopeintegration
  Running setup.py develop for example.zopeaddon
  Running setup.py develop for example.ploneintegration
  Running setup.py develop for example.ploneaddon
  Running setup.py develop for example.multipleeps
  Running setup.py develop for example.metaoverrides
  Running setup.py develop for example.different2
  Running setup.py develop for example.different
  Running setup.py develop for example.basetestpackage
  Running setup.py develop for example.addon
Successfully installed example.addon-1.0a1 example.basetestpackage-1.0a1 example.different-1.0a1 example.different2-1.0a1 example.metaoverrides-1.0a1 example.multipleeps-1.0a1 example.ploneaddon-1.0a1 example.ploneintegration-1.0a1 example.zopeaddon-1.0a1 example.zopeintegration namespaceexample.native namespaceexample.pkgutilns plone.autoinclude-1.0.0a1 six-1.16.0 zope.configuration-4.4.0 zope.event-4.5.0 zope.exceptions-4.4 zope.i18nmessageid-5.0.1 zope.interface-5.4.0 zope.schema-6.1.0 zope.testrunner-5.3.0
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/command_context.py", line 20, in main_context
    yield
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/base_command.py", line 98, in main
    return self._main(args)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/base_command.py", line 214, in _main
    self.handle_pip_version_check(options)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/req_command.py", line 144, in handle_pip_version_check
    options, retries=0, timeout=min(5, options.timeout)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/req_command.py", line 94, in _build_session
    index_urls=self._get_index_urls(options),
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/network/session.py", line 289, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/network/session.py", line 150, in user_agent
    if sys.platform.startswith("darwin") and platform.mac_ver()[0]:
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/platform.py", line 615, in mac_ver
    info = _mac_ver_xml()
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/platform.py", line 591, in _mac_ver_xml
    with open(fn, 'rb') as f:
OSError: [Errno 24] Too many open files: '/System/Library/CoreServices/SystemVersion.plist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/runpy.py", line 196, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/__main__.py", line 31, in <module>
    sys.exit(_main())
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/base_command.py", line 98, in main
    return self._main(args)
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/cli/command_context.py", line 20, in main_context
    yield
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/utils/temp_dir.py", line 75, in tempdir_registry
    yield _tempdir_registry
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/utils/temp_dir.py", line 37, in global_tempdir_manager
    _tempdir_manager = old_tempdir_manager
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/utils/temp_dir.py", line 165, in __exit__
    self.cleanup()
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/utils/temp_dir.py", line 184, in cleanup
    rmtree(self._path)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_vendor/tenacity/__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_vendor/tenacity/__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_vendor/tenacity/__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_vendor/tenacity/__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_vendor/tenacity/__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/site-packages/pip/_internal/utils/misc.py", line 135, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/shutil.py", line 413, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/Users/maurits/.pyenv/versions/pypy3.7-7.3.5/lib-python/3/shutil.py", line 409, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/private/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/pip-ephem-wheel-cache-tz_ttpt8'

================================================================================================================= log end ==================================================================================================================
ERROR: could not install deps [zope.testrunner, -e., -etest-packages/example.basetestpackage, -etest-packages/example.addon, -etest-packages/example.different, -etest-packages/example.different2, -etest-packages/example.metaoverrides, -etest-packages/example.ploneaddon, -etest-packages/example.ploneintegration, -etest-packages/example.zopeaddon, -etest-packages/example.zopeintegration, -etest-packages/example.multipleeps, -etest-packages/namespaceexample.native, -etest-packages/namespaceexample.pkgutilns]; v = InvocationError('/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/bin/python -m pip install zope.testrunner -e. -etest-packages/example.basetestpackage -etest-packages/example.addon -etest-packages/example.different -etest-packages/example.different2 -etest-packages/example.metaoverrides -etest-packages/example.ploneaddon -etest-packages/example.ploneintegration -etest-packages/example.zopeaddon -etest-packages/example.zopeintegration -etest-packages/example.multipleeps -etest-packages/namespaceexample.native -etest-packages/namespaceexample.pkgutilns', 1)
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
ERROR:   pypy3-integration: could not install deps [zope.testrunner, -e., -etest-packages/example.basetestpackage, -etest-packages/example.addon, -etest-packages/example.different, -etest-packages/example.different2, -etest-packages/example.metaoverrides, -etest-packages/example.ploneaddon, -etest-packages/example.ploneintegration, -etest-packages/example.zopeaddon, -etest-packages/example.zopeintegration, -etest-packages/example.multipleeps, -etest-packages/namespaceexample.native, -etest-packages/namespaceexample.pkgutilns]; v = InvocationError('/Users/maurits/community/plone-coredev/py3/src/plone.autoinclude/.tox/pypy3-integration/bin/python -m pip install zope.testrunner -e. -etest-packages/example.basetestpackage -etest-packages/example.addon -etest-packages/example.different -etest-packages/example.different2 -etest-packages/example.metaoverrides -etest-packages/example.ploneaddon -etest-packages/example.ploneintegration -etest-packages/example.zopeaddon -etest-packages/example.zopeintegration -etest-packages/example.multipleeps -etest-packages/namespaceexample.native -etest-packages/namespaceexample.pkgutilns', 1)

real	1m29.964s
user	0m17.772s
sys	0m2.506s
```

When I check with `ulimit -n` I see the open file limit is 256.
I raise it to 400 with `ulimit -n 400`

I run tox again and it finishes in 24 seconds.
After this, I can reset the file limit to 256 and tox even finishes in 4 seconds.
But when the tox environment needs to be recreated because of a change, the file limit is hit again, making it slow and fail.

Note: changing the open files limit with `ulimit` only has effect on the current shell.
In a new shell or after a restart, you are back to the old value.
So either you do this in your bash or other shell config, or you find a different way.
There seem to be various ways, depending on your Mac version, and some need a restart.
Anyway, I am not going to recommend one way here.

Aftermath:
The biggest problem was that tox failed.
But with a higher limit, the run not only succeeds, but is faster.
So increasing the limit may be a fine idea in general.
But I am definitely no expert in this area.

I do want to see what this does for `pip install Plone`, which at the moment takes so long that I quit it.
Workaround is to use the deprecated dependency resolver.
Maybe more open files makes the new default pip dependency resolver faster.