Fix tests with buildout 4, and add tests with buildout 5.
This is needed because we get more namespace packages.
Error in the [scheduled test](https://github.com/plone/plone.autoinclude/actions/runs/17890615198/job/50870454923#step:5:97):

```
ModuleNotFoundError: No module named 'zc.recipe.testrunner'
```